grails-app/domain/com/gamews/domains/Scores.groovy
package com.gamews.domains

class Scores {

	String totalCoins
	String score
	String userUUID
	Date dateCreated
	Date lastUpdate
	Boolean status = true
	
    static constraints = {
		
    }
}

grails-app/controllers/com/gamews/domains/ScoresController.groovy
package com.gamews.domains



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ScoresController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Scores.list(params), model:[scoresInstanceCount: Scores.count()]
    }

    def show(Scores scoresInstance) {
        respond scoresInstance
    }

    def create() {
        respond new Scores(params)
    }

    @Transactional
    def save(Scores scoresInstance) {
        if (scoresInstance == null) {
            notFound()
            return
        }

        if (scoresInstance.hasErrors()) {
            respond scoresInstance.errors, view:'create'
            return
        }

        scoresInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'scoresInstance.label', default: 'Scores'), scoresInstance.id])
                redirect scoresInstance
            }
            '*' { respond scoresInstance, [status: CREATED] }
        }
    }

    def edit(Scores scoresInstance) {
        respond scoresInstance
    }

    @Transactional
    def update(Scores scoresInstance) {
        if (scoresInstance == null) {
            notFound()
            return
        }

        if (scoresInstance.hasErrors()) {
            respond scoresInstance.errors, view:'edit'
            return
        }

        scoresInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Scores.label', default: 'Scores'), scoresInstance.id])
                redirect scoresInstance
            }
            '*'{ respond scoresInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Scores scoresInstance) {

        if (scoresInstance == null) {
            notFound()
            return
        }

        scoresInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Scores.label', default: 'Scores'), scoresInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'scoresInstance.label', default: 'Scores'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/scores/_form.gsp
<%@ page import="com.gamews.domains.Scores" %>



<div class="fieldcontain ${hasErrors(bean: scoresInstance, field: 'score', 'error')} ">
	<label for="score">
		<g:message code="scores.score.label" default="Score" />
		
	</label>
	<g:textField name="score" value="${scoresInstance?.score}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: scoresInstance, field: 'totalCoins', 'error')} ">
	<label for="totalCoins">
		<g:message code="scores.totalCoins.label" default="Total Coins" />
		
	</label>
	<g:textField name="totalCoins" value="${scoresInstance?.totalCoins}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: scoresInstance, field: 'userUUID', 'error')} ">
	<label for="userUUID">
		<g:message code="scores.userUUID.label" default="User UUID" />
		
	</label>
	<g:textField name="userUUID" value="${scoresInstance?.userUUID}"/>

</div>

grails-app/views/scores/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scores.label', default: 'Scores')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-scores" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-scores" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${scoresInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${scoresInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:scoresInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/scores/edit.gsp
<%@ page import="com.gamews.domains.Scores" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scores.label', default: 'Scores')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-scores" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-scores" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${scoresInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${scoresInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:scoresInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${scoresInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/scores/index.gsp
<%@ page import="com.gamews.domains.Scores" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scores.label', default: 'Scores')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-scores" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-scores" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="score" title="${message(code: 'scores.score.label', default: 'Score')}" />
					
						<g:sortableColumn property="totalCoins" title="${message(code: 'scores.totalCoins.label', default: 'Total Coins')}" />
					
						<g:sortableColumn property="userUUID" title="${message(code: 'scores.userUUID.label', default: 'User UUID')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${scoresInstanceList}" status="i" var="scoresInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${scoresInstance.id}">${fieldValue(bean: scoresInstance, field: "score")}</g:link></td>
					
						<td>${fieldValue(bean: scoresInstance, field: "totalCoins")}</td>
					
						<td>${fieldValue(bean: scoresInstance, field: "userUUID")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${scoresInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/scores/show.gsp
<%@ page import="com.gamews.domains.Scores" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'scores.label', default: 'Scores')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-scores" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-scores" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list scores">
			
				<g:if test="${scoresInstance?.score}">
				<li class="fieldcontain">
					<span id="score-label" class="property-label"><g:message code="scores.score.label" default="Score" /></span>
					
						<span class="property-value" aria-labelledby="score-label"><g:fieldValue bean="${scoresInstance}" field="score"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${scoresInstance?.totalCoins}">
				<li class="fieldcontain">
					<span id="totalCoins-label" class="property-label"><g:message code="scores.totalCoins.label" default="Total Coins" /></span>
					
						<span class="property-value" aria-labelledby="totalCoins-label"><g:fieldValue bean="${scoresInstance}" field="totalCoins"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${scoresInstance?.userUUID}">
				<li class="fieldcontain">
					<span id="userUUID-label" class="property-label"><g:message code="scores.userUUID.label" default="User UUID" /></span>
					
						<span class="property-value" aria-labelledby="userUUID-label"><g:fieldValue bean="${scoresInstance}" field="userUUID"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:scoresInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${scoresInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>